name: Run IPTV Scraper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 手动触发运行

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 确保使用正确的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py script
        run: |
          python main.py

      # 将生成的所有 .txt 文件推送到仓库
      - name: Commit and push .txt files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add *.txt  # 添加所有生成的 .txt 文件
          git commit -m "Add generated txt files"
          git push
        # 避免无更改时导致的错误
        continue-on-error: true  
