name: Run Python Script

on:
  workflow_dispatch:  # 可以手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 设置 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyGithub

      - name: Run main.py
        run: python main.py

      - name: Commit and push updated files
        run: |
          git config --local user.name "MemoryCollection"
          git config --local user.email "csszue@gamil.com"
          git add *.txt  # 添加所有 .txt 文件
          git commit -m "Update text files after running main.py" || echo "No changes to commit"
          git push origin main  # 直接推送到 main 分支
