name: Python CI with GitHub Actions

on:
  # 手动触发
  workflow_dispatch:

  # 每 8 小时触发一次
  schedule:
    - cron: '0 */8 * * *'  # 每 8 小时执行一次，UTC 时间

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 可以根据需要修改 Python 版本

    # 安装依赖
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # 运行 main.py 脚本
    - name: Run main.py script
      run: |
        python main.py

    # 提交并推送更改到 GitHub 仓库
    - name: Commit and push changes
      run: |
        git config --global user.name "MemoryCollection"
        git config --global user.email "csszue@gmail.com"
        git add .
        git commit -m "Automated file update" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 会自动提供 GITHUB_TOKEN
